version: '3.8'
services:
  db:
    image: mariadb:10.11
    restart: always
    ports:
      - "7082:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 67b7f471fa16819e
      MYSQL_DATABASE: bloggy
      MYSQL_USER: user
      MYSQL_PASSWORD: 67b7f471fa16819e
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
      - "7081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: 67b7f471fa16819e

volumes:
  db_data:
